window.__LANGUAGES__ = {
  "en": {
    "hero_headline": "SWEET BONANZA BONUS WHEEL SPIN FOR 200 FREE SPINS",
    "hero_brand": "SWEET BONANZA",
    "hero_prefix": "BONUS WHEEL SPIN FOR",
    "hero_free_spins": "200 FREE SPINS",
    "hero_description": "Spin the wheel and grab 200 Free Spins for Sweet Bonanza or up to +500% on your first top-up on loot.run",
    "hero_spin": "Spin the wheel and grab",
    "hero_free": "200 Free Spins",
    "hero_for_sweet": "for Sweet Bonanza or up to",
    "hero_500": "+500%",
    "hero_first": "on your first top-up on",
    "hero_loot": "loot.run",
    "promo_special_promo": "SPECIAL PROMO",
    "promo_free_spins": "200 FREE SPINS",
    "promo_for_game": "for Sweet Bonanza",
    "promo_up_to_bonus": "UP TO +500%",
    "promo_first_deposit": "on your first deposit",
    "stats_spins_today_label": "SPINS TODAY",
    "stats_spins_today_value": "2 473",
    "stats_bonuses_claimed_label": "BONUSES CLAIMED",
    "stats_bonuses_claimed_value": "1 092",
    "footer_no_deposit_needed": "No deposit needed to spin.",
    "footer_bonus_activation_text": "Bonus is activated after registration and first top-up on loot.run.",
    "unlock_youve_unlocked": "YOU'VE UNLOCKED",
    "unlock_a_sweet_bonus": "A SWEET BONUS",
    "unlock_up_to": "up to",
    "unlock_percent": "500%",
    "unlock_on_first": "on your first",
    "unlock_deposit_at": "deposit at loot.run",
    "claim_bonus_button": "Claim bonus",
    "try_again_button": "Try again",
    "bonus_activated_after_registration_and_first_deposit": "Bonus is activated after registration and first deposit on loot.run",
    "almost_done": "ALMOST DONE",
    "steps_intro": "Follow the steps to claim your Sweet Bonanza bonus on loot.run",
    "step1_title": "STEP 1",
    "step1_text": "Create an account or Log In on loot.run.",
    "step2_title": "STEP 2",
    "step2_text": "Make your first deposit.",
    "step3_title": "STEP 3",
    "step3_text": "Get up to +500% bonus and Free Spins for Sweet Bonanza.",
    "continue_to": "Continue to LOOT.RUN",
    "redirect_message": "You will be redirected to loot.run in a new tab.",
    "offer_new_players_only": "Offer available for new players only. 18+"
  },
  "ru": {
    "hero_headline": "ВРАЩАЙ КОЛЕСО БОНУСОВ И ПОЛУЧИ 200 ФРИСПИНОВ",
    "hero_brand": "ВРАЩАЙ КОЛЕСО",
    "hero_prefix": "БОНУСОВ И ПОЛУЧИ",
    "hero_free_spins": "200 ФРИСПИНОВ",
    "hero_description": "Вращай колесо и получи 200 фриспинов для Sweet Bonanza или до +500% на первый депозит на loot.run",
    "hero_spin": "Вращай колесо и получи",
    "hero_free": "200 фриспинов",
    "hero_for_sweet": "для Sweet Bonanza или до",
    "hero_500": "+500%",
    "hero_first": "на первый депозит на",
    "hero_loot": "loot.run",
    "promo_special_promo": "СПЕЦИАЛЬНОЕ ПРЕДЛОЖЕНИЕ",
    "promo_free_spins": "200 ФРИСПИНОВ",
    "promo_for_game": "для Sweet Bonanza",
    "promo_up_to_bonus": "ДО +500%",
    "promo_first_deposit": "на первый депозит",
    "stats_spins_today_label": "СПИНОВ СЕГОДНЯ",
    "stats_spins_today_value": "2 473",
    "stats_bonuses_claimed_label": "БОНУСОВ АКТИВИРОВАНО",
    "stats_bonuses_claimed_value": "1 092",
    "footer_no_deposit_needed": "Для вращения не нужен депозит.",
    "footer_bonus_activation_text": "Бонус активируется после регистрации и первого пополнения счета на loot.run.",
    "unlock_youve_unlocked": "ВЫ ОТКРЫЛИ",
    "unlock_a_sweet_bonus": "СЛАДКИЙ БОНУС",
    "unlock_up_to": "до",
    "unlock_percent": "500%",
    "unlock_on_first": "на первый",
    "unlock_deposit_at": "депозит на loot.run",
    "claim_bonus_button": "Получить бонус",
    "try_again_button": "Попробовать снова",
    "bonus_activated_after_registration_and_first_deposit": "Бонус активируется после регистрации и первого депозита на loot.run",
    "almost_done": "ПОЧТИ ГОТОВО",
    "steps_intro": "Выполните шаги, чтобы получить бонус Sweet Bonanza на loot.run",
    "step1_title": "ШАГ 1",
    "step1_text": "Создайте аккаунт или войдите на loot.run.",
    "step2_title": "ШАГ 2",
    "step2_text": "Внесите первый депозит.",
    "step3_title": "ШАГ 3",
    "step3_text": "Получите до +500% бонуса и фриспины для Sweet Bonanza.",
    "continue_to": "Перейти на LOOT.RUN",
    "redirect_message": "Вы будете перенаправлены на loot.run в новой вкладке.",
    "offer_new_players_only": "Предложение доступно только для новых игроков. 18+"
  },
  "uz": {
    "hero_headline": "BONUSLAR G'ILDIRAGINI AYLANTIR VA 200 TA BEPUL AYLANTIRISHLARNI OL",
    "hero_brand": "BONUSLAR G'ILDIRAGINI",
    "hero_prefix": "AYLANTIR VA 200 TA",
    "hero_free_spins": "BEPUL AYLANTIRISHLARNI OL",
    "hero_description": "G'ildirakni aylantir va Sweet Bonanza uchun 200 ta aylantirish yoki birinchi depozit uchun loot.run da +500% gacha ol",
    "hero_spin": "G'ildirakni aylantir va Sweet Bonanza",
    "hero_free": "200 ta aylantirish",
    "hero_for_sweet": " yoki birinchi depozit uchun",
    "hero_500": "+500%",
    "hero_first": "gacha ol",
    "hero_loot": "loot.run",
    "promo_special_promo": "MAXSUS TAKLIF",
    "promo_free_spins": "200 TA BEPUL AYLANTIRISH",
    "promo_for_game": "Sweet Bonanza uchun",
    "promo_up_to_bonus": "+500% GACHA",
    "promo_first_deposit": "birinchi depozit uchun",
    "stats_spins_today_label": "BUGUNGI SPINLAR",
    "stats_spins_today_value": "2 473",
    "stats_bonuses_claimed_label": "FAOLLASHTIRILGAN BONUSLAR",
    "stats_bonuses_claimed_value": "1 092",
    "footer_no_deposit_needed": "Aylantirish uchun cepozit kerak emas",
    "footer_bonus_activation_text": "Bonus ro'yxatdan o'tish va loot.run da birinchi hisob to'ldirishdan keyin faollashtiriladi",
    "unlock_youve_unlocked": "SIZ SHIRIN",
    "unlock_a_sweet_bonus": "BONUS OCHDINGIZ",
    "unlock_up_to": "gacha",
    "unlock_percent": "500%",
    "unlock_on_first": "loot.run dagi",
    "unlock_deposit_at": "birinchi depozit uchun",
    "claim_bonus_button": "Bonusni olish",
    "try_again_button": "Yana urinib ko'rish",
    "bonus_activated_after_registration_and_first_deposit": "Bonus ro'yxatdan o'tish va loot.run da birinchi hisob to'ldirishdan keyin faollashtiriladi",
    "almost_done": "DEYARLI TAYYOR",
    "steps_intro": "loot.run da Sweet Bonanza bonusini olish uchun quyidagi qadamlarni amalga oshiring",
    "step1_title": "1-QADAM",
    "step1_text": "Hisob qaydi oching va loot.run ga kiring.",
    "step2_title": "2- QADAM",
    "step2_text": "Depozit kiriting",
    "step3_title": "3-QADAM",
    "step3_text": "+500% gacha bonus yoki Sweet Bonanza uchun bepul aylantirishlar oling",
    "continue_to": "LOOT.RUN ga o'ting",
    "redirect_message": "Siz yangi yorliqda loot.run ga qayta yo'naltirilasiz",
    "offer_new_players_only": "Taklif faqat yangi o'yinchilar uchun mavjud. 18+"
  }
};
